### ISSUE TITLE
Component/SectionHeader

### ISSUE THREAD

**Issue by ayakaki** [qin-team-recipe/06-recipe-app#39]
https://www.figma.com/file/JSVMGHBeYzAsmujXjPDwAE/%E4%B8%80%E6%B5%81%E3%83%AC%E3%82%B7%E3%83%94?type=design&node-id=126-349&mode=design&t=irNkGBGHFd6gOQAK-4

![image](https://github.com/qin-team-recipe/06-recipe-app/assets/65984887/e80ea2ad-2c62-43da-9410-31fa2bb6efbf)

**Comment by yanachuwan9sm** [comment]
Title -> SectionHeader に修正
