### ISSUE TITLE
Component/HeroImage

### ISSUE THREAD

**Issue by ayakaki** [qin-team-recipe/06-recipe-app#42]
https://www.figma.com/file/JSVMGHBeYzAsmujXjPDwAE/%E4%B8%80%E6%B5%81%E3%83%AC%E3%82%B7%E3%83%94?type=design&node-id=6726-3577&mode=dev

![Image](https://github.com/qin-team-recipe/06-recipe-app/assets/95360878/098d0660-aa52-4e6d-b2a1-0a8398a4d30c)

**Comment by yanachuwan9sm** [comment]
シェフ詳細画面では使われなくなったため、普遍的なコンポーネント名に修正。サムネイル画像も修正。
