### ISSUE TITLE
Component/SmallChef

### ISSUE THREAD

**Issue by ayakaki** [qin-team-recipe/06-recipe-app#48]
https://www.figma.com/file/JSVMGHBeYzAsmujXjPDwAE/%E4%B8%80%E6%B5%81%E3%83%AC%E3%82%B7%E3%83%94?type=design&node-id=262-952&mode=design&t=irNkGBGHFd6gOQAK-4

![image](https://github.com/qin-team-recipe/06-recipe-app/assets/65984887/3b1fe8cc-dc94-48fa-9254-c9b83baf4cb4)

**Comment by yanachuwan9sm** [comment]
#50 がdoneしたのでclose
