### ISSUE TITLE
Component/HorizontalSmallChefList

### ISSUE THREAD

**Issue by ayakaki** [qin-team-recipe/06-recipe-app#49]
https://www.figma.com/file/JSVMGHBeYzAsmujXjPDwAE/%E4%B8%80%E6%B5%81%E3%83%AC%E3%82%B7%E3%83%94?type=design&node-id=262-941&mode=design&t=irNkGBGHFd6gOQAK-4

![image](https://github.com/qin-team-recipe/06-recipe-app/assets/65984887/441f8c5b-d33a-40b8-aeeb-ce3d09c0437e)

**Comment by yanachuwan9sm** [comment]
#50 がdoneしたのでclose
