### ISSUE TITLE
Component/Chef

### ISSUE THREAD

**Issue by ayakaki** [qin-team-recipe/06-recipe-app#50]
https://www.figma.com/file/JSVMGHBeYzAsmujXjPDwAE/%E4%B8%80%E6%B5%81%E3%83%AC%E3%82%B7%E3%83%94?type=design&node-id=6714-8739&mode=design&t=irNkGBGHFd6gOQAK-4

![image](https://github.com/qin-team-recipe/06-recipe-app/assets/65984887/e50effd7-03bc-4782-b6ea-b1206daa57c4)

**Comment by yanachuwan9sm** [comment]
下記もこのissueに紐付けて作業
#48 
#49 
#51 
#52 
#53
