### ISSUE TITLE
Component/HorizontalChefList

### ISSUE THREAD

**Issue by ayakaki** [qin-team-recipe/06-recipe-app#51]
https://www.figma.com/file/JSVMGHBeYzAsmujXjPDwAE/%E4%B8%80%E6%B5%81%E3%83%AC%E3%82%B7%E3%83%94?type=design&node-id=6714-8779&mode=design&t=irNkGBGHFd6gOQAK-4

![image](https://github.com/qin-team-recipe/06-recipe-app/assets/65984887/71abbd3a-a0b7-4eab-a3a5-4667c89aa48d)

**Comment by yanachuwan9sm** [comment]
#50 がdoneしたのでclose
