### ISSUE TITLE
Component/VerticalChefListItem

### ISSUE THREAD

**Issue by ayakaki** [qin-team-recipe/06-recipe-app#52]
https://www.figma.com/file/JSVMGHBeYzAsmujXjPDwAE/%E4%B8%80%E6%B5%81%E3%83%AC%E3%82%B7%E3%83%94?type=design&node-id=199-504&mode=design&t=irNkGBGHFd6gOQAK-4

![image](https://github.com/qin-team-recipe/06-recipe-app/assets/65984887/dfece5c0-126b-4cbb-81ef-bab5e2130e77)

**Comment by yanachuwan9sm** [comment]
#50 がdoneしたのでclose
