### ISSUE TITLE
Component/VerticalChefList

### ISSUE THREAD

**Issue by ayakaki** [qin-team-recipe/06-recipe-app#53]
https://www.figma.com/file/JSVMGHBeYzAsmujXjPDwAE/%E4%B8%80%E6%B5%81%E3%83%AC%E3%82%B7%E3%83%94?type=design&node-id=126-792&mode=design&t=irNkGBGHFd6gOQAK-4

![image](https://github.com/qin-team-recipe/06-recipe-app/assets/65984887/1b0abda8-64e9-47b9-8500-8668a0616fe1)

**Comment by yanachuwan9sm** [comment]
#50 がdoneしたのでclose
