### ISSUE TITLE
Component/ChefDetail

### ISSUE THREAD

**Issue by ayakaki** [qin-team-recipe/06-recipe-app#54]
https://www.figma.com/file/JSVMGHBeYzAsmujXjPDwAE/%E4%B8%80%E6%B5%81%E3%83%AC%E3%82%B7%E3%83%94?type=design&node-id=126-792&mode=design&t=irNkGBGHFd6gOQAK-4

<img width="421" alt="image" src="https://github.com/qin-team-recipe/06-recipe-app/assets/95360878/194db3b4-f96d-45c7-9cd6-17ed882ad74e">

**Comment by yanachuwan9sm** [comment]
先日FIXされたデザインをもとに、ChefDetailも更新されるっぽいです！
<img width="421" alt="image" src="https://github.com/qin-team-recipe/06-recipe-app/assets/95360878/194db3b4-f96d-45c7-9cd6-17ed882ad74e">
