### ISSUE TITLE
Component/TwoTab

### ISSUE THREAD

**Issue by ayakaki** [qin-team-recipe/06-recipe-app#66]
https://www.figma.com/file/JSVMGHBeYzAsmujXjPDwAE/%E4%B8%80%E6%B5%81%E3%83%AC%E3%82%B7%E3%83%94?type=design&node-id=658-2863&mode=design&t=irNkGBGHFd6gOQAK-4

![image](https://github.com/qin-team-recipe/06-recipe-app/assets/65984887/f8f2d082-4eb8-412f-ad0e-d8a2fe64f3c3)

**Comment by yanachuwan9sm** [comment]
TwoTabのstorybookさえあれば、`TabItemForTwo`コンポーネントのストーリは不要そう。
そもそも、`ThreeTab`は必要そうですか？(FIXデザインには存在していない) -> とりあえず TwoTabのStorybookの中に入れ込む。

**Comment by yanachuwan9sm** [comment]
以下もこのissueで同時作業
https://github.com/qin-team-recipe/06-recipe-app/issues/35
https://github.com/qin-team-recipe/06-recipe-app/issues/36
